# Generated by Django 5.2.3 on 2025-07-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0002_grnsummary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grnsummary',
            unique_together={('grn_number', 'po_number', 'seller_invoice_number')},
        ),
        migrations.AddIndex(
            model_name='grnsummary',
            index=models.Index(fields=['grn_number', 'po_number', 'seller_invoice_number'], name='grn_summary_grn_num_cfa295_idx'),
        ),
    ]
