# Generated by Django 5.2.3 on 2025-07-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0004_invoiceitemreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='manually_enter',
            field=models.CharField(blank=True, help_text='Key entered manually from frontend', max_length=100, null=True, verbose_name='Manually enter'),
        ),
        migrations.AddField(
            model_name='invoiceitemdata',
            name='manually_enter',
            field=models.CharField(blank=True, help_text='Key entered manually from frontend', max_length=100, null=True, verbose_name='Manually Enter'),
        ),
    ]
