# Generated by Django 5.2.3 on 2025-07-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0005_invoicedata_manually_enter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='data_uploaded',
            field=models.BooleanField(default=False, verbose_name='Data Uploaded'),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='invoice_extracted',
            field=models.BooleanField(default=False, verbose_name='Invoice Extracted'),
        ),
    ]
