# Generated by Django 5.2.3 on 2025-07-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0006_uploadhistory_data_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='extracted_invoice_count',
            field=models.IntegerField(default=0, help_text='Number of invoices extracted for this upload', verbose_name='Extracted Invoice Count'),
        ),
    ]
