# Generated by Django 5.2.3 on 2025-07-22 06:59

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_question', models.TextField()),
                ('matched_tables', models.JSONField(help_text='Tables matched for this question')),
                ('generated_sql', models.TextField(blank=True, null=True)),
                ('sql_result', models.JSONField(blank=True, null=True)),
                ('natural_response', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Conversation',
                'verbose_name_plural': 'Chat Conversations',
                'db_table': 'chatbot_conversation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='chatbot_con_session_6c660a_idx'), models.Index(fields=['created_at'], name='chatbot_con_created_e6d9d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TableSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('schema_description', models.TextField(help_text='Human-readable description of the table')),
                ('columns_info', models.JSONField(help_text='Detailed column information')),
                ('sample_questions', models.JSONField(help_text='Sample questions this table can answer')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='Vector embedding of the schema description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table Schema',
                'verbose_name_plural': 'Table Schemas',
                'db_table': 'chatbot_table_schema',
                'indexes': [models.Index(fields=['table_name'], name='chatbot_tab_table_n_de5044_idx')],
            },
        ),
    ]
